/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.chromo.gui;

import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.jtattoo.plaf.mint.MintLookAndFeel;
import com.sun.java.swing.plaf.motif.MotifLookAndFeel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.multi.MultiLookAndFeel;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.plaf.synth.SynthLookAndFeel;
import javax.swing.table.DefaultTableModel;
import ru.chromo.objects.ChromosomeSet;
import ru.chromo.objects.Chromosome;
import ru.chromo.objects.Computer;

public class Form extends javax.swing.JFrame {

    ArrayList<Computer> computers;
    ArrayList<ComputerInitPanel> compPans;
    ChromosomeSet set;
    
    
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        compPans = new ArrayList<>();
        for (int i = 0; i < 2; i++) {
            compPans.add(new ComputerInitPanel(i+1));
            panCenter.add(compPans.get(i));
        }
        
        pack();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view = new javax.swing.JFrame();
        tabPaneView = new javax.swing.JTabbedPane();
        best = new javax.swing.JFrame();
        scBest = new javax.swing.JScrollPane();
        panCenter = new javax.swing.JPanel();
        panBottom = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        spPopSize = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        spWorksSize = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        spIterations = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        btnAddComp = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();

        view.setTitle("Вычисления");
        view.getContentPane().setLayout(new java.awt.GridLayout(0, 1));
        view.getContentPane().add(tabPaneView);

        best.setTitle("Результат");
        best.getContentPane().add(scBest, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Установочные данные");

        panCenter.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        getContentPane().add(panCenter, java.awt.BorderLayout.CENTER);

        panBottom.setPreferredSize(new java.awt.Dimension(315, 120));
        panBottom.setLayout(new java.awt.GridLayout(0, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridLayout(0, 2));

        jLabel13.setText("Размер популяции");
        jPanel1.add(jLabel13);

        spPopSize.setMinimumSize(new java.awt.Dimension(40, 20));
        spPopSize.setPreferredSize(new java.awt.Dimension(40, 20));
        spPopSize.setValue((int)5);
        jPanel1.add(spPopSize);

        jPanel4.add(jPanel1);

        jLabel14.setText("Количество заданий");
        jPanel2.add(jLabel14);

        spWorksSize.setMinimumSize(new java.awt.Dimension(40, 20));
        spWorksSize.setPreferredSize(new java.awt.Dimension(40, 20));
        spWorksSize.setValue((int)10);
        jPanel2.add(spWorksSize);

        jPanel4.add(jPanel2);

        jLabel15.setText("Количество поколений");
        jPanel3.add(jLabel15);

        spIterations.setMinimumSize(new java.awt.Dimension(40, 20));
        spIterations.setPreferredSize(new java.awt.Dimension(40, 20));
        spIterations.setValue((int)1);
        jPanel3.add(spIterations);

        jPanel4.add(jPanel3);

        btnAddComp.setText("Добавить компьютер");
        btnAddComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCompActionPerformed(evt);
            }
        });
        jPanel5.add(btnAddComp);

        jPanel4.add(jPanel5);

        panBottom.add(jPanel4);

        btnRun.setText("Начать выполнение");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });
        panBottom.add(btnRun);

        getContentPane().add(panBottom, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        computers = new ArrayList<>(); //обновлять графику при рестарте
        int iterations = (int)spIterations.getValue();
        for (ComputerInitPanel panel : compPans) {
            computers.add( new Computer( 
                new Double(panel.getTxtDelayLevel().getText()), 
                new Double(panel.getTxtRate().getText()), 
                (panel.getCbGenType().getSelectedIndex()+1) ));
        }
        
        set = new ChromosomeSet( (Integer)(spPopSize.getValue()), (Integer)(spWorksSize.getValue()), computers );
        
        
        for (int i = 0; i < iterations; i++) {
            System.out.println("ITER "+(i+1));
            
            ChromosomeSet set;
            JTabbedPane pane = new JTabbedPane();
            
            if(i==0) {
                set = this.set;
            }
            else {
                set = new ChromosomeSet((Integer)(spPopSize.getValue()), (Integer)(spWorksSize.getValue()), computers, this.set.nPop);
            }
            
            //отрисовка расчетов хромосом
            JPanel panView = new JPanel(new GridLayout(0, 1));
            for (int j = 0; j < set.pop.size(); j++) {
                panView.add(set.pop.get(j).renderChromosome(j + 1));
            }
            pane.add("Расчет хромосом", new JScrollPane(panView));
            //===========================
            //отрисовка результатов сверки полученных значений довер-ых интервалов
            //с заданными значениями
            set.operationCheck();
//            pane.add("Сверка значений", new JScrollPane(set.operationCheck()));
            //===========================
            //отрисовка результатов операции кроссинговера
            pane.add("Операция кроссинговера", new JScrollPane(set.operationCrossover()));
            //===========================
            //отрисовка результатов операции мутации
            pane.add("Операция мутации", new JScrollPane(set.operationMutation()));
            //===========================
            //отрисовка результатов целевой функции
            pane.add("Вычисление целевой функции", new JScrollPane(set.objectiveFunc()));
            //===========================
            //отрисовка результатов селекции хромосом
            pane.add("Селекция хромосом", new JScrollPane(set.selectionFunc()));
            //===========================
            this.set = set;
            tabPaneView.add("Поколение "+(i+1), pane);
        }
        

        view.pack();
        view.revalidate();
        view.setPreferredSize(new Dimension(1100, 600));
        view.setSize(new Dimension(1100, 600));
        view.setLocationRelativeTo(null);
        view.setVisible(true);

        //вывод лучшей хромосомы
        JPanel p = new JPanel();
        p.add( set.finalResult.renderChromosome(set.finalIdx+1) );
        scBest.setViewportView(p);
//        scBest.add(p, BorderLayout.CENTER);
        best.pack();
        best.setVisible(true);
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnAddCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCompActionPerformed
        compPans.add(new ComputerInitPanel(compPans.size()+1));
        panCenter.add(compPans.get(compPans.size()-1));
        pack();
        revalidate();
        
    }//GEN-LAST:event_btnAddCompActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new AcrylLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame best;
    private javax.swing.JButton btnAddComp;
    private javax.swing.JButton btnRun;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panBottom;
    private javax.swing.JPanel panCenter;
    private javax.swing.JScrollPane scBest;
    private javax.swing.JSpinner spIterations;
    private javax.swing.JSpinner spPopSize;
    private javax.swing.JSpinner spWorksSize;
    private javax.swing.JTabbedPane tabPaneView;
    private javax.swing.JFrame view;
    // End of variables declaration//GEN-END:variables
}
